function errors = Errors(expO, aproxO)
    % Evitar errores de división por cero
    exp = expO + 10;
    aprox = aproxO + 10;
    
    Il = ...
        [...
            sum(abs(exp(:,1) - aprox(:,1))) / length(exp(:,1));
            sum(abs((exp(:,1) - aprox(:,1))./exp(:,1))) / length(exp(:,1))*1e2 ...
        ];
    Vc = ...
        [
            sum(abs(exp(:,2) - aprox(:,2))) / length(exp(:,2)); ...
            sum(abs((exp(:,2) - aprox(:,2))./exp(:,2))) / length(exp(:,2))*1e2 ...
        ];
    Vl = ...
        [
            sum(abs(exp(:,3) - aprox(:,3))) / length(exp(:,3)); ...
            sum(abs((exp(:,3) - aprox(:,3))./exp(:,3))) / length(exp(:,3))*1e2 ...
        ];
    Ic = ...
        [
            sum(abs(exp(:,4) - aprox(:,4))) / length(exp(:,4)); ...
            sum(abs((exp(:,4) - aprox(:,4))./exp(:,4))) / length(exp(:,4))*1e2 ...
        ];

    errors = table(Il,Vc,Vl,Ic,'RowNames',{'Mae'; 'Mape'});
end
