%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\kevin\A\Instrumentacion\Practicas\Practica5\TablaDeValores.ods
%    Worksheet: Capacitor
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2024/05/03 17:46:43

%% Import the data
[~, ~, raw] = xlsread('C:\Users\kevin\A\Instrumentacion\Practicas\Practica5\TablaDeValores.ods','Capacitor','A2:H13');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
ValoresVc = table;

%% Allocate imported array to column variable names
ValoresVc.FrecuenciaHz = data(:,1);
ValoresVc.FrecuenciaRadSeg = data(:,2);
ValoresVc.VE = data(:,3);
ValoresVc.VS = data(:,4);
ValoresVc.T = data(:,5);
ValoresVc.D = data(:,6);
ValoresVc.M = data(:,7);
ValoresVc.A = data(:,8)*-1;

%% Clear temporary variables
clearvars data raw;