%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\kevin\A\Instrumentacion\Practicas\Practica5\TablaDeValores.ods
%    Worksheet: Inductor
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2024/05/03 17:46:15

%% Import the data
[~, ~, raw] = xlsread('C:\Users\kevin\A\Instrumentacion\Practicas\Practica5\TablaDeValores.ods','Inductor','A2:I14');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
ValoresIl = table;

%% Allocate imported array to column variable names
ValoresIl.FrecuenciaHz = data(:,1);
ValoresIl.FrecuenciaRadSeg = data(:,2);
ValoresIl.VE = data(:,3);
ValoresIl.VS = data(:,4);
ValoresIl.IL = data(:,5);
ValoresIl.T = data(:,6);
ValoresIl.D = data(:,7);
ValoresIl.M = data(:,8);
ValoresIl.A = data(:,9)*-1;

%% Clear temporary variables
clearvars data raw;